### ISSUE TITLE
OSX 10.11 运行不能

### ISSUE THREAD

**Issue by rekcah1986** [mmagi/VocalShimeji#1]
java.lang.RuntimeException: /Users/xxx/Downloads/VocalShimeji/lib/win32-x86_64/libjnidispatch.dylib文件未找到.
    at com.group_finity.mascot.Main.checkJnaDll(Main.java:101)
    at com.group_finity.mascot.Main.LoadDlls(Main.java:120)
    at vocalshimeji.theme.hijikata_toushirou.VocalShimeji.main(VocalShimeji.java:43)

无意中发现这个项目的，期待~

**Comment by mmagi** [comment]
http://pan.baidu.com/s/1CFCBp#path=%252Fkagura

只有这个测试的版本里才打包好了mac版本的app哦……
这个项目的管理神游了，于是一直没有发布这个

**Comment by rekcah1986** [comment]
哈哈，运行成功，非常感谢，貌似现在很少有人玩这个了
